version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: seguro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TMKTtmkt123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks:
      - seguro-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # PropostaService
  proposta-service:
    build:
      context: .
      dockerfile: Dockerfile.proposta
    container_name: seguro-proposta-service
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=propostadb;Username=postgres;Password=TMKTtmkt123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - seguro-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ContratacaoService
  contratacao-service:
    build:
      context: .
      dockerfile: Dockerfile.contratacao
    container_name: seguro-contratacao-service
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=contratacaodb;Username=postgres;Password=TMKTtmkt123
      - PropostaServiceUrl=http://proposta-service:5000
    depends_on:
      postgres:
        condition: service_healthy
      proposta-service:
        condition: service_healthy
    networks:
      - seguro-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:


networks:
  seguro-network:
    driver: bridge
